Re-pulled with latest documentation changes. (#33)
* Updated all reference to the db name dart_test to be conduit_test_db. Changed the default password to conduit! to make it easier to remember given we are publishing this password anyway.

* removed the unused context_helpers.dart

* replaced all references to aqueduct to conduit.

* Fixed lints.

* Fixed a secondary bug. If the proxy fails to initialise then _server was initialised causing a secondary error on shutdown.

* The run_unit_test script now starts and waits for postgress to be running and resets the db if required.

* Expanded the no. of acceptable characters for the password. Migrated to using the new PostgresManager class.

* Created a script to start the postgres deamon and create the database to make it easy to run single unit tests from vscode.

* Fixed incorrect port mappings for the socket proxy.

* Removed dart files no longer used.

* Fixed a failed unit test as the method documentOperationResponse did not match the signature of the super it overrides.

* Added notes on the new startup_db.dart script for unit tests.

* changed start_db.dart to always recreate the user/db.

* Released 2.0.0-a3

* migrated the documentation from branch doc/source into the main branch as per the dart project structure guidelines.

* Additional renames of aqueduct to conduit.

* added .gitbook.yaml configuration.

* fixed path to doc root.

* removed an empty level of directory structure.

* change root path to docs and set the home page.

* GitBook: [develop] 84 pages and 17 assets modified

* GitBook: [develop] one page modified

* Update .gitbook.yaml

* renamed index.md to README.md as gitbooks was being difficult and not reading the index.md file.

* updated to use readme.md as the root page.

* GitBook: [develop] 3 pages modified

* GitBook: [develop] 81 pages modified

* GitBook: [develop] 2 pages modified

* GitBook: [develop] 11 pages modified

* GitBook: [develop] 5 pages modified

* GitBook: [develop] 9 pages modified

* GitBook: [develop] 12 pages modified

* Release alpha (#26)

* Fixing the way aqueduct TestRequest serializes list query parameters (#4)

* Fixing the way aqueduct TestRequest serializes list query parameters

Up until now list query parameters were serialized in such a way:
`url?query=[1, 2]`. This is not the way aqueduct expects list parameters to
be sent with that pull request the way lists are serialized is:
`url?query=1&query=2`

* Update aqueduct_test/test/request_test.dart

* Nnbd ingegrate deps (#14)

* Fixing problem with deps

* Fixed all Uri errors

* Add back templates

* Change test and main package to version 2.12

* Add workflow back (#15)

* Create dart.yml

* remove macos build

* remove windows test

 Error: Container operations are only supported on Linux runners

* whoops

* remove travis and move appveyor to ci for posterity

* remove badges

* granularize workflows

* Remove caching (#16)

* Create dart.yml

* remove macos build

* remove windows test

 Error: Container operations are only supported on Linux runners

* whoops

* remove travis and move appveyor to ci for posterity

* remove badges

* granularize workflows

* remove cache

* remove cache

* Merge open api and commons (#17)

* Create dart.yml

* remove macos build

* remove windows test

 Error: Container operations are only supported on Linux runners

* whoops

* GitBook: [master] 2 pages and 17 assets modified

* remove travis and move appveyor to ci for posterity

* remove badges

* granularize workflows

* Updated code to use conduit_common and conduit_open_api

* remove cache

* remove cache

Co-authored-by: Brett Sutton <bsutton@noojee.com.au>

* renamed top level directories from aqueduct to conduit.

* change all reference to aqueduct to conduit.

* renamed referencese from Aqueduct to Conduit

* updated packages to a series of renames from aqueduct to conduit.

* Moved templates to their own repo conduit_templates

* Now cleanly compiles with with all of the newly named packags.

* All compiler errors resulting from nnbd migration have now been resolved.

* migrated to nnbd.

* Base map type takes a key? so had to mark as as covarient as tests wouldn't even start.

* databaseType is optional.

* corrected the defaultTo of address to be explicitly 0.0.0.0

* corrected the names of the certs to use conduit rather than aqueduct.

* All serve_test unit tests are passing after sorting out a few nnbd issues.

* Attempts to fixe the can provide a single outage unit test. Still not working correctly.

* update changelog

* fix bin

* fix up changelogs

* ignored test generated code.

* move dummy config to not_test

* minor cleanup

* changelog

* pedantic was necessary

* upgrade test dep

* Moved the PostgresTestConfig into the package conduit_common_test and updated all unit tests to use the new configuration. Also updated ci to use the new default db settings.

* Manually merged some changes from upstream.

* manually merge from upstream.

* corrected indentation and removed bogus key from copy/paste fail.

* Updated pubspec to pull conduit_test from pub.dev now that it is published.

* broadened the version no. so works with any 2.0 version of conduit.

* Released 2.0.0-a3

* fix up unit tests

* Fixed permission issues with the postgres user setup

* switch back to 15432

* "break" tests

* Unit tests now all pass - most of the time. (#28)

* Updated all reference to the db name dart_test to be conduit_test_db. Changed the default password to conduit! to make it easier to remember given we are publishing this password anyway.

* removed the unused context_helpers.dart

* replaced all references to aqueduct to conduit.

* Fixed lints.

* Fixed a secondary bug. If the proxy fails to initialise then _server was initialised causing a secondary error on shutdown.

* The run_unit_test script now starts and waits for postgress to be running and resets the db if required.

* Expanded the no. of acceptable characters for the password. Migrated to using the new PostgresManager class.

* Created a script to start the postgres deamon and create the database to make it easy to run single unit tests from vscode.

* Fixed incorrect port mappings for the socket proxy.

* Removed dart files no longer used.

* Fixed a failed unit test as the method documentOperationResponse did not match the signature of the super it overrides.

* Added notes on the new startup_db.dart script for unit tests.

* changed start_db.dart to always recreate the user/db.

* Released 2.0.0-a3

* migrated the documentation from branch doc/source into the main branch as per the dart project structure guidelines.

* Additional renames of aqueduct to conduit.

* added .gitbook.yaml configuration.

* fixed path to doc root.

* removed an empty level of directory structure.

* change root path to docs and set the home page.

* GitBook: [develop] 84 pages and 17 assets modified

* GitBook: [develop] one page modified

* Update .gitbook.yaml

* renamed index.md to README.md as gitbooks was being difficult and not reading the index.md file.

* updated to use readme.md as the root page.

* GitBook: [develop] 3 pages modified

* GitBook: [develop] 81 pages modified

* GitBook: [develop] 2 pages modified

* GitBook: [develop] 11 pages modified

* GitBook: [develop] 5 pages modified

* GitBook: [develop] 9 pages modified

* GitBook: [develop] 12 pages modified

* Second PR. Mostly documentation updates. (#29)

* Updated all reference to the db name dart_test to be conduit_test_db. Changed the default password to conduit! to make it easier to remember given we are publishing this password anyway.

* removed the unused context_helpers.dart

* replaced all references to aqueduct to conduit.

* Fixed lints.

* Fixed a secondary bug. If the proxy fails to initialise then _server was initialised causing a secondary error on shutdown.

* The run_unit_test script now starts and waits for postgress to be running and resets the db if required.

* Expanded the no. of acceptable characters for the password. Migrated to using the new PostgresManager class.

* Created a script to start the postgres deamon and create the database to make it easy to run single unit tests from vscode.

* Fixed incorrect port mappings for the socket proxy.

* Removed dart files no longer used.

* Fixed a failed unit test as the method documentOperationResponse did not match the signature of the super it overrides.

* Added notes on the new startup_db.dart script for unit tests.

* changed start_db.dart to always recreate the user/db.

* Released 2.0.0-a3

* migrated the documentation from branch doc/source into the main branch as per the dart project structure guidelines.

* Additional renames of aqueduct to conduit.

* added .gitbook.yaml configuration.

* fixed path to doc root.

* removed an empty level of directory structure.

* change root path to docs and set the home page.

* GitBook: [develop] 84 pages and 17 assets modified

* GitBook: [develop] one page modified

* Update .gitbook.yaml

* renamed index.md to README.md as gitbooks was being difficult and not reading the index.md file.

* updated to use readme.md as the root page.

* GitBook: [develop] 3 pages modified

* GitBook: [develop] 81 pages modified

* GitBook: [develop] 2 pages modified

* GitBook: [develop] 11 pages modified

* GitBook: [develop] 5 pages modified

* GitBook: [develop] 9 pages modified

* GitBook: [develop] 12 pages modified

* hopefully this fixes the adapter tests

* use 15432 for template test db port

* this is why we need a mono repo

* changed password back

Co-authored-by: Reductions <slavi.boyanov@gmail.com>
Co-authored-by: Brett Sutton <bsutton@noojee.com.au>

* GitBook: [develop] one page modified

* GitBook: [develop] one page modified

Co-authored-by: j4qfrost <j4qfrost@gmail.com>
Co-authored-by: Reductions <slavi.boyanov@gmail.com>